name: HHR Chatbot deployment

on:
  push:
    branches:
      - prod

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: 1. Checkout
        uses: actions/checkout@v2

      - name: 2. Run Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org/'

      - name: 3. Install dependencies
        run: yarn install

      - name: 4. Build react app
        run: yarn build

      - name: 5. Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 6. Deploy to S3
        run: aws s3 sync dist s3://${{secrets.AWS_BUCKET_NAME}} --delete

      - name: 7. Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
